baseURL = "/"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "themes"
title = "Marion Miller Jewellery"
[[menu.footer]]
name = "Information"
url = "/info/"
weight = 3
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Bracelets"
url = "/bracelets/"
weight = 4
[[menu.main]]
name = "Pendants"
url = "/pendants/"
weight = 3
[[menu.main]]
name = "Earrings"
url = "/earrings/"
weight = 2
[[menu.main]]
name = "Rings"
url = "/rings/"
weight = 1
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.homepage_meta_tags]
meta_description = "Unique Handmade Jewellery - An exclusive collection of handcrafted jewellery by Marion Miller in her workshop on Stronsay, Orkney."
meta_og_description = "Unique Handmade Jewellery - An exclusive collection of handcrafted jewellery. Made by Marion Miller in her workshop on Stronsay, Orkney."
meta_og_image = ""
meta_og_title = "Marion Miller Jewellery"
meta_og_type = "Handmade Jewellery"
meta_og_url = "https://mmjewellery.netlify.com"
meta_twitter_card = "summary"
meta_twitter_creator = ""
meta_twitter_site = ""
[params.logo]
alt = "Marion Miller Jewellery"
mobile = "images/logo-mobile.jpg"
standard = "images/logo.svg"
