baseURL = "/"
languageCode = "en-us"
title = "Marion Miller Jewellery"
themesDir = "themes"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-mobile.jpg"
    standard  = "images/logo.svg"
    alt = "Marion Miller Jewellery"

  [params.homepage_meta_tags]
    meta_description = "Unique Handmade Jewellery - An exclusive collection of handcrafted jewellery by Marion Miller in her workshop on Stronsay, Orkney."
    meta_og_title = "Marion Miller Jewellery"
    meta_og_type = "Handmade Jewellery"
    meta_og_url = "https://mmjewellery.netlify.com"
    meta_og_image = ""
    meta_og_description = "Unique Handmade Jewellery - An exclusive collection of handcrafted jewellery. Made by Marion Miller in her workshop on Stronsay, Orkney."
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[menu]
  # Main Menu
  [[menu.main]]
    name = "Rings"
    url = "/rings/"
      weight = 1
 
  [[menu.main]]
    name = "Earrings"
    url = "/earrings/"
      weight = 2
      
  [[menu.main]]
    name = "Pendants"
    url = "/pendants/"
      weight = 3
      
  [[menu.main]]
    name = "Bracelets"
    url = "/bracelets/"
      weight = 4

  #[[menu.main]]
  #    name = "Team"
  #    url = "/team/"
  #    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
      
  [[menu.footer]]
    name = "Information"
    url = "/info/"
      weight = 3
